In [2]:
#Importing necessary librarires 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import spacy
import nltk
import string
string.punctuation
s = string.punctuation

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
import pickle

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\omkar/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [10]:
df = pd.read_json("c:\\Users\\omkar\\AppData\\Local\\Temp\\Cell_Phones_and_Accessories_5 (2).json"
                  , lines=True)
# keep only the desired columns
df = df[['reviewText', 'overall', 'summary']]

In [12]:
df.sample(10)

,reviewText,overall,summary
37477,This is perfect to remove the strange pentalob...,5,This is perfect.
18198,"It does what it's supposed to, glad to buy it....",4,Buy it
79708,I've been using this mount for a few weeks now...,5,Works great - does what it promises
110143,This arm band fits perfectly around my arm and...,4,fits perfectly
128609,"when this arrived, the first night i had it so...",5,I don't care!!! I love it!!
182882,I honestly love this cable. It is a very innov...,4,Works well...
112643,"Bought a brand new iPhone and loved it, but my...",4,Fantastic case
138071,This is by far the bet case cover....Ringke sl...,5,I love it
119688,"As usual, for every iphone i get i need a slim...",5,Perfect
113296,"Very nice, compact charger, works perfectly wh...",5,Works well!

In [ ]:
#Workflow Of project
#1. Data Cleaning
#2. Data Preprocessing

In [14]:
#DATA CLEANING

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194439 entries, 0 to 194438
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   reviewerID      194439 non-null  object
 1   asin            194439 non-null  object
 2   reviewerName    190920 non-null  object
 3   helpful         194439 non-null  object
 4   reviewText      194439 non-null  object
 5   overall         194439 non-null  int64
 6   summary         194439 non-null  object
 7   unixReviewTime  194439 non-null  int64
 8   reviewTime      194439 non-null  object
dtypes: int64(2), object(7)
memory usage: 13.4+ MB

In [15]:
df.columns

Index(['reviewText', 'overall', 'summary'], dtype='object')

In [16]:
print(df.head())

                                          reviewText  overall  \
0  They look good and stick good! I just don't li...        4
1  These stickers work like the review says they ...        5
2  These are awesome and make my phone look so st...        5
3  Item arrived in great time and was in perfect ...        4
4  awesome! stays on, and looks great. can be use...        5

                                     summary
0                                 Looks Good
1                      Really great product.
2                             LOVE LOVE LOVE
3                                      Cute!
4  leopard home button sticker for iphone 4s

In [17]:
#Not keeping 3-star reviews as they are neutral
#and do not contribute to the sentiment analysis
df = df[df['overall'] != 3]

In [18]:
#Converting ratings to binary  labels: 
#1 for positive reviews (4 and 5 stars)
#0 for negative reviews (1 and 2 stars)

def sentiment_label(ratings):
    if ratings >= 4:
        return 1
    else:
        return 0
    
df["sentiment(label)"] = df["overall"].apply(sentiment_label)

In [19]:
df.head()

,reviewText,overall,summary,sentiment(label)
0,They look good and stick good! I just don't li...,4,Looks Good,1
1,These stickers work like the review says they ...,5,Really great product.,1
2,These are awesome and make my phone look so st...,5,LOVE LOVE LOVE,1
3,Item arrived in great time and was in perfect ...,4,Cute!,1
4,"awesome! stays on, and looks great. can be use...",5,leopard home button sticker for iphone 4s,1

In [20]:
#Combining reviewText and summary into single columns for better analysis
df["Review"] = df["reviewText"] + " " + df["summary"]
df = df[["Review", "sentiment(label)"]]

In [21]:
df.head()

                                              Review  sentiment(label)
0  They look good and stick good! I just don't li...                 1
1  These stickers work like the review says they ...                 1
2  These are awesome and make my phone look so st...                 1
3  Item arrived in great time and was in perfect ...                 1
4  awesome! stays on, and looks great. can be use...                 1